### ISSUE TITLE
Theme Management

### ISSUE THREAD

**Issue by cdemetriadis** [design-ops/stylable-swiftui#42]
## Option A
A single theme file contains all variations of the theme. All tokens will be preceded by their theme variant, except the default theme. eg:

* /body
* @dark/body
* @new-year/body

Requires changes to Plugin, Assistants & Stylist

## Option B
We maintain different files for each theme variation.

* theme-file.sketch
* theme-file-dark.sketch
* theme-file-new-year.sketch

The app will manage the themes internally.
UI Maintanence will be far larger as we'll need to maintain multiple files for the theme variations.

**Comment by kerrmarin** [comment]
So as I understand with option A (so far my preferred option) we'd have the option to set different themes in the stylist via some interface e.g.:

```swift
let stylist = Stylist.create()
stylist.setTheme(.dark) // or stylist.setTheme("dark")
```

The stylist then internally looks at the theme set and prepends that to any identifier that needs matched. 

So the code we write for styles is always the same e.g.:

```swift
Text("This is a test").style("products/header/title")
```

And inside the `style` method (or some other point inside the `Stylist`) we handle the logic for the theme.

If so, we need changes in:

- The convertor to extract themes from identifiers e.g. anything prepended with `@` (only needed if we want to use a type for themes)
- The stylist, to take the theme that's been set and append it to the stylist

@deanWombourne if you're happy with this I'll start working on a PR

**Comment by deanWombourne** [comment]
Hey.

s/setTheme/theme - this isn't Java ;)

And do we know how theme would affect precedence?

I.e. *.button.title(dark) vs. search.button.title - would specifying the
theme apply the first, or would specifying the area (search in the example)
override it?

I think this sounds like a great idea.

S

On 16 Jul 2021 at 09:19, Kerr Marín Miller ***@***.***>
wrote:

So as I understand with option A (so far my preferred option) we'd have the
option to set different themes in the stylist via some interface e.g.:

let stylist = Stylist.create()
stylist.setTheme(.dark) // or stylist.setTheme("dark")

The stylist then internally looks at the theme set and prepends that to any
identifier that needs matched.

So the code we write for styles is always the same e.g.:

Text("This is a test").style("products/header/title")

And inside the style method (or some other point inside the Stylist) we
handle the logic for the theme.

If so, we need changes in:

   - The convertor to extract themes from identifiers e.g. anything
   prepended with @ (only needed if we want to use a type for themes)
   - The stylist, to take the theme that's been set and append it to the
   stylist

@deanWombourne <https://github.com/deanWombourne> if you're happy with this
I'll start working on a PR

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/design-ops/stylable-swiftui/issues/42#issuecomment-881267360>,
or unsubscribe

**Comment by kerrmarin** [comment]
Good point. I'll write a test for that 😃
